{
 "title": "Klima",
 "description": "Rt",
 "tags": [ "Kl" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "run",
    "query": "SHOW TAG VALUES FROM dev WITH KEY = \"run\""
   },
   { "name": "measurement", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"temp\") FROM /^$measurement$/ WHERE (\"run\" =~ /^$run$/ AND \"location\" = 'livingroom')",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    },
    {
     "alias": "bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "bedroom" }
     ]
    }
   ]
  },
  {
   "title": "IAQ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"iaq\") FROM /^$measurement$/ WHERE (\"run\" =~ /^$run$/ AND \"location\" = 'livingroom')",
     "select": [
      [
       { "params": [ "iaq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    }
   ]
  },
  {
   "title": "Indoor Air Quality",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "iaq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    },
    {
     "alias": "bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "iaq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "bedroom" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"press\") FROM /^$measurement$/ WHERE (\"run\" =~ /^$run$/ AND \"location\" = 'livingroom')",
     "select": [
      [
       { "params": [ "press" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "press" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    },
    {
     "alias": "bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "press" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "bedroom" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "raspizero1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"humi\") FROM /^$measurement$/ WHERE (\"run\" =~ /^$run$/ AND \"location\" = 'livingroom')",
     "select": [
      [
       { "params": [ "humi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 5, "y": 21 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "humi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    },
    {
     "alias": "bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "humi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "bedroom" }
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ohm" }
   ],
   "targets": [
    {
     "alias": "livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "gas" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    },
    {
     "alias": "bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "gas" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "bedroom" }
     ]
    },
    {
     "alias": "livingroom baseline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "gasbaseline" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "livingroom" }
     ]
    },
    {
     "alias": "bedroom baseline",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "gasbaseline" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$run$/" },
      { "condition": "AND", "key": "location", "operator": "=", "value": "bedroom" }
     ]
    }
   ]
  },
  {
   "title": "Raw data from InfluxDB",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 35 },
   "targets": [
    {
     "measurement": "dev",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}